#define PluginName TEXT("DialogueGraph")
#define DialogueGraphTab1 TEXT("DialogueGraphMainTab")
#define DialogueGraphTab2 TEXT("DialogueGraphPropTab")
#define DialogueGraphAppModeName TEXT("DialogueGraphAppMode")
#define DialogueGraphCategoryKey FName("DialogueGraph")
#define DialogueGraphEditorStyle TEXT("DialogueGraphEditorStyle")